/****************************************************************************
  Generated by TypeWriter - don't make any changes in this file
****************************************************************************/

declare interface ApiResult<T> {
  data: null | T; // T 
  isSuccess: boolean;
  error: string;
}

