/****************************************************************************
  Generated by TypeWriter - don't make any changes in this file
****************************************************************************/

/** Структура архива */
declare interface ArchiveViewModel {
  /** Архивные страницы */
  pages: PageViewModel[];
  /** Архивные виджеты */
  widgets: WidgetViewModel[];
}

