/****************************************************************************
  Generated by TypeWriter - don't make any changes in this file
****************************************************************************/

declare interface CultureModel {
  id: number;
  title: string;
  name: string;
}

