/****************************************************************************
  Generated by TypeWriter - don't make any changes in this file
****************************************************************************/

declare interface CustomActionModel {
  id: number;
  code: string;
  itemIdParamName: string;
  cultureParamName: string;
  regionParamName: string;
  previewPagePathName: string;
}

