/****************************************************************************
  Generated by TypeWriter - don't make any changes in this file
****************************************************************************/

/** Модель для окончательного удаления элемента */
declare interface DeleteModel {
  /** Id элемента */
  itemId: number;
  /** Удалить все версии */
  isDeleteAllVersions?: null | boolean; // boolean 
}

