/****************************************************************************
  Generated by TypeWriter - don't make any changes in this file
****************************************************************************/

declare interface DiscriminatorModel {
  id: number;
  isArchive: boolean;
  discriminator: string;
  typeName: string;
  isPage: boolean;
  title: string;
  description: string;
  iconUrl: string;
  preferredContentId?: null | number; // number 
}

