/****************************************************************************
  Generated by TypeWriter - don't make any changes in this file
****************************************************************************/

/** Модель для редактирования */
declare interface EditModel {
  /** Id элемента */
  itemId: number;
  /** Заголовок */
  title: string;
}

