/****************************************************************************
  Generated by TypeWriter - don't make any changes in this file
****************************************************************************/

declare interface EditModel {
  itemId: number;
  title: string;
  isInSiteMap: boolean;
}

