/****************************************************************************
  Generated by TypeWriter - don't make any changes in this file
****************************************************************************/

declare interface ExtensionFieldModel {
  fieldName: string;
  typeName: string;
  typeDescription: string;
  value: null | any; // any 
  relationExtensionId?: null | number; // number 
  attributeId: number;
}

