/****************************************************************************
  Generated by TypeWriter - don't make any changes in this file
****************************************************************************/

declare interface QpContentModel {
  id: number;
  fields: QpFieldModel[];
}

