/****************************************************************************
  Generated by TypeWriter - don't make any changes in this file
****************************************************************************/

/** Модель QP контента с его полями */
declare interface QpContentViewModel {
  /** Идентификатор контента */
  id: number;
  /** Поля контента */
  fields: QpFieldViewModel[];
}

