/****************************************************************************
  Generated by TypeWriter - don't make any changes in this file
****************************************************************************/

declare interface QpFieldModel {
  fieldId: string;
  name: string;
}

