/****************************************************************************
  Generated by TypeWriter - don't make any changes in this file
****************************************************************************/

/** Модель с полями контента */
declare interface QpFieldViewModel {
  /** Идентификатор поля контента */
  fieldId: string;
  /** Название контента */
  name: string;
}

