/****************************************************************************
  Generated by TypeWriter - don't make any changes in this file
****************************************************************************/

declare interface RegionViewModel {
  id: number;
  alias: string;
  parentId?: null | number; // number 
  title: string;
  children: RegionViewModel[];
  hasChildren: boolean;
}

