/****************************************************************************
  Generated by TypeWriter - don't make any changes in this file
****************************************************************************/

/** Модель для перемещения элемена в архив */
declare interface RemoveModel {
  /** Id элемента */
  itemId: number;
  /** Удалять все версии */
  isDeleteAllVersions?: null | boolean; // boolean 
  /** Удалить контентную версию */
  isDeleteContentVersions?: null | boolean; // boolean 
  /** Id контентной версии, которую не удалять, а оставить в качестве полноценной страницы.  Возможно только при условии IsDeleteAllVersions == false и IsDeleteContentVersions == false */
  contentVersionId?: null | number; // number 
}

