/****************************************************************************
  Generated by TypeWriter - don't make any changes in this file
****************************************************************************/

/** Модель для изменения отображаемой сортировки страниц */
declare interface ReorderModel {
  /** Id страницы, позицию которой хотим изменить */
  itemId: number;
  /** Id страницы, рядом с которой хотим поместить страницу */
  relatedItemId: number;
  /** Признак - переместить страницу ItemId перед страницей RelatedItemId */
  isInsertBefore: boolean;
}

