/****************************************************************************
  Generated by TypeWriter - don't make any changes in this file
****************************************************************************/

/** Восстановление из архива, возможно только  в случае наличия родительского элемента не в архиве */
declare interface RestoreModel {
  /** Id элемента */
  itemId: number;
  /** Восстанавливать все версии */
  isRestoreAllVersions?: null | boolean; // boolean 
  /** Восстанавливать виджеты */
  isRestoreWidgets?: null | boolean; // boolean 
  /** Восстанавливать контентные верисс */
  isRestoreContentVersions?: null | boolean; // boolean 
  /** Восстанавлявать дочерние элементы */
  isRestoreChildren?: null | boolean; // boolean 
}

