apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: wp-admin-deployment
  namespace: widget-platform-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wp-admin
  template:
    metadata:
      labels:
        app: wp-admin
    spec:
      containers:
      - image: spbdocker03:5000/widget-platform/admin:||version||
        name: wp-admin
        ports:
        - containerPort: 80
        env:
        - name: ConfigurationServiceUrl
          value: http://configuration-service.dpc-consolidation
        - name: ConfigurationServiceToken
          value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJRUC5Db25maWd1cmF0aW9uU2VydmljZS5Jc3N1ZXIiLCJleHAiOjE1Nzg1ODM4NjIsImF1ZCI6IlFQLkNvbmZpZ3VyYXRpb25TZXJ2aWNlLkF1ZGllbmNlIn0.wN-we_Wezxtv3rtLn3mEQ9tZngPwfgn45Ta7kLfKO-Q
        resources: 
          limits:
            memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: wp-admin-service
  namespace: widget-platform-ns
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: wp-admin
