apiVersion: apps/v1
kind: Deployment
metadata:
  name: wp-admin
  namespace: widget-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wp-admin
  template:
    metadata:
      labels:
        app: wp-admin
        logging: enabled        
    spec:
      containers:
      - image: "||registry||/widget-platform/admin:||version||"
        name: wp-admin
        ports:
        - containerPort: 80
        envFrom:
          - configMapRef:
              name: qp-config
        env:
        - name: ConfigurationServiceUrl
          valueFrom:
            configMapKeyRef:
              name: qp-config
              key: CONFIGURATION_SERVICE_HOST
        - name: ConfigurationServiceToken
          valueFrom:
            configMapKeyRef:
              name: qp-config
              key: CONFIGURATION_SERVICE_TOKEN
        volumeMounts:
          - name: time-config
            mountPath: /etc/localtime
            subPathExpr: $(TZ)
          - name: timezone-config
            mountPath: /etc/timezone
            subPath: TZ             
        resources: 
          limits:
            memory: "256Mi"
      volumes:
        - name: time-config
          hostPath:
            path: /usr/share/zoneinfo
        - name: timezone-config
          configMap: 
            name: qp-config
            items:
            - key: TZ
              path: TZ         
---
apiVersion: v1
kind: Service
metadata:
  name: wp-admin
  namespace: widget-platform
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: wp-admin
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
  name: wp-admin
  namespace: widget-platform
spec:
  rules:
  - host: __host__
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: wp-admin
            port:
              number: 80

