//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QA.Engine.Administration.WebApp.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Texts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Texts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QA.Engine.Administration.WebApp.Core.Resources.Texts", typeof(Texts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить подраздел.
        /// </summary>
        public static string AddItem {
            get {
                return ResourceManager.GetString("AddItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить версию.
        /// </summary>
        public static string AddVersionItem {
            get {
                return ResourceManager.GetString("AddVersionItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alias.
        /// </summary>
        public static string Alias {
            get {
                return ResourceManager.GetString("Alias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Архивировать.
        /// </summary>
        public static string Archive {
            get {
                return ResourceManager.GetString("Archive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Архив.
        /// </summary>
        public static string ArchiveMenu {
            get {
                return ResourceManager.GetString("ArchiveMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Инфо.
        /// </summary>
        public static string CommonTab {
            get {
                return ResourceManager.GetString("CommonTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Контентные версии.
        /// </summary>
        public static string ContentVersionTab {
            get {
                return ResourceManager.GetString("ContentVersionTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактировать.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to История изменений.
        /// </summary>
        public static string History {
            get {
                return ResourceManager.GetString("History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показывать в структуре сайта.
        /// </summary>
        public static string IsInSiteMap {
            get {
                return ResourceManager.GetString("IsInSiteMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Переместить.
        /// </summary>
        public static string Move {
            get {
                return ResourceManager.GetString("Move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип действия.
        /// </summary>
        public static string PopupActionType {
            get {
                return ResourceManager.GetString("PopupActionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить.
        /// </summary>
        public static string PopupAddButton {
            get {
                return ResourceManager.GetString("PopupAddButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить раздел.
        /// </summary>
        public static string PopupAddItemTitle {
            get {
                return ResourceManager.GetString("PopupAddItemTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить версию.
        /// </summary>
        public static string PopupAddVersionItemTitle {
            get {
                return ResourceManager.GetString("PopupAddVersionItemTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить виджет.
        /// </summary>
        public static string PopupAddWidgetTitle {
            get {
                return ResourceManager.GetString("PopupAddWidgetTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Архивировать.
        /// </summary>
        public static string PopupArchive {
            get {
                return ResourceManager.GetString("PopupArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Архивировать все версии.
        /// </summary>
        public static string PopupArchiveAllVersion {
            get {
                return ResourceManager.GetString("PopupArchiveAllVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Архивировать.
        /// </summary>
        public static string PopupArchiveButton {
            get {
                return ResourceManager.GetString("PopupArchiveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отправить в архив.
        /// </summary>
        public static string PopupArchiveItemTitle {
            get {
                return ResourceManager.GetString("PopupArchiveItemTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отмена.
        /// </summary>
        public static string PopupCancelButton {
            get {
                return ResourceManager.GetString("PopupCancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить все версии.
        /// </summary>
        public static string PopupDeleteAllVersion {
            get {
                return ResourceManager.GetString("PopupDeleteAllVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить.
        /// </summary>
        public static string PopupDeleteButton {
            get {
                return ResourceManager.GetString("PopupDeleteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete item.
        /// </summary>
        public static string PopupDeleteItemTitle {
            get {
                return ResourceManager.GetString("PopupDeleteItemTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Алиас.
        /// </summary>
        public static string PopupFieldAlias {
            get {
                return ResourceManager.GetString("PopupFieldAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to alias.
        /// </summary>
        public static string PopupFieldAliasPlaceholder {
            get {
                return ResourceManager.GetString("PopupFieldAliasPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип контента.
        /// </summary>
        public static string PopupFieldContentType {
            get {
                return ResourceManager.GetString("PopupFieldContentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название.
        /// </summary>
        public static string PopupFieldTitle {
            get {
                return ResourceManager.GetString("PopupFieldTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название раздела.
        /// </summary>
        public static string PopupFieldTitlePlaceholder {
            get {
                return ResourceManager.GetString("PopupFieldTitlePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Версия.
        /// </summary>
        public static string PopupFieldVersion {
            get {
                return ResourceManager.GetString("PopupFieldVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Переместить.
        /// </summary>
        public static string PopupMoveButton {
            get {
                return ResourceManager.GetString("PopupMoveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Переместить страницу.
        /// </summary>
        public static string PopupMoveTitle {
            get {
                return ResourceManager.GetString("PopupMoveTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сменить версию.
        /// </summary>
        public static string PopupMoveVersion {
            get {
                return ResourceManager.GetString("PopupMoveVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Применить.
        /// </summary>
        public static string PopupReorderButton {
            get {
                return ResourceManager.GetString("PopupReorderButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to После.
        /// </summary>
        public static string PopupReorderInsertAfter {
            get {
                return ResourceManager.GetString("PopupReorderInsertAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to До.
        /// </summary>
        public static string PopupReorderInsertBefore {
            get {
                return ResourceManager.GetString("PopupReorderInsertBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Переместить.
        /// </summary>
        public static string PopupReorderInsertLabel {
            get {
                return ResourceManager.GetString("PopupReorderInsertLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменить сортировку.
        /// </summary>
        public static string PopupReorderTitle {
            get {
                return ResourceManager.GetString("PopupReorderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Восстановить версии.
        /// </summary>
        public static string PopupRestoreAllVersion {
            get {
                return ResourceManager.GetString("PopupRestoreAllVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Восстановить.
        /// </summary>
        public static string PopupRestoreButton {
            get {
                return ResourceManager.GetString("PopupRestoreButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Восстановить вложенные страницы.
        /// </summary>
        public static string PopupRestoreChildren {
            get {
                return ResourceManager.GetString("PopupRestoreChildren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Восстановить контентные версии.
        /// </summary>
        public static string PopupRestoreContentVersion {
            get {
                return ResourceManager.GetString("PopupRestoreContentVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Восстановить раздел.
        /// </summary>
        public static string PopupRestoreItemTitle {
            get {
                return ResourceManager.GetString("PopupRestoreItemTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Восстановить виджеты.
        /// </summary>
        public static string PopupRestoreWidget {
            get {
                return ResourceManager.GetString("PopupRestoreWidget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Контентная.
        /// </summary>
        public static string PopupVersionContent {
            get {
                return ResourceManager.GetString("PopupVersionContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Структурная.
        /// </summary>
        public static string PopupVersionStructural {
            get {
                return ResourceManager.GetString("PopupVersionStructural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Публиковать.
        /// </summary>
        public static string Publish {
            get {
                return ResourceManager.GetString("Publish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Опубликовано.
        /// </summary>
        public static string Published {
            get {
                return ResourceManager.GetString("Published", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обновить.
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сортировать.
        /// </summary>
        public static string Reorder {
            get {
                return ResourceManager.GetString("Reorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Восстановить.
        /// </summary>
        public static string Restore {
            get {
                return ResourceManager.GetString("Restore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите режим показа.
        /// </summary>
        public static string SelectMode {
            get {
                return ResourceManager.GetString("SelectMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите регион.
        /// </summary>
        public static string SelectRegion {
            get {
                return ResourceManager.GetString("SelectRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите тип.
        /// </summary>
        public static string SelectType {
            get {
                return ResourceManager.GetString("SelectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показать алиас.
        /// </summary>
        public static string ShowAlias {
            get {
                return ResourceManager.GetString("ShowAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показать поля расширения.
        /// </summary>
        public static string ShowExtensionField {
            get {
                return ResourceManager.GetString("ShowExtensionField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показать ID.
        /// </summary>
        public static string ShowID {
            get {
                return ResourceManager.GetString("ShowID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показать путь.
        /// </summary>
        public static string ShowPath {
            get {
                return ResourceManager.GetString("ShowPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Управление Сайтом.
        /// </summary>
        public static string SiteManagement {
            get {
                return ResourceManager.GetString("SiteManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Карта Сайта.
        /// </summary>
        public static string SiteMapMenu {
            get {
                return ResourceManager.GetString("SiteMapMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заголовок.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип контента.
        /// </summary>
        public static string TypeName {
            get {
                return ResourceManager.GetString("TypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Просмотр.
        /// </summary>
        public static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Видимый.
        /// </summary>
        public static string Visible {
            get {
                return ResourceManager.GetString("Visible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Виджеты.
        /// </summary>
        public static string WidgetTab {
            get {
                return ResourceManager.GetString("WidgetTab", resourceCulture);
            }
        }
    }
}
